# -*- coding: utf-8 -*-

categories = [
    {'Beverages': [
        'Apple Juice',        
        'Carbonated water',
        'Coffee',
        'Cranberry juice',
        'Fruit Punch',
        'Lemonade',
        'Limeade',
        'Orange Juice',
        'Soda',
        'Smoothie',
        'Water'
    ]},

    {'Bread, Cereal, and Pastries': [
        'Cereal',
        'Cookies',
        'Danish',
        'Muffin',
        'Multi-Grain Bread',
        'Oat Bread',
        'Pie',
        'Potato Bread',
        'Taco',
        'Tortilla',
        'Tostada',
        'White Bread',
        'Wheat Bread'
    ]},

    {'Chips, Nuts, Candies, and Others': [
        'Almonds',
        'Candy',
        'Cashews',
        'Cashew Butter',
        'Chocolate',
        'Dark Chocolate',
        'Jam',
        'Peanuts',
        'Peanut Butter',
        'Potato chips',
        'Corn chips'
    ]},

    {'Condiments': [
        'Barbecue Sauce',
        'Chipotle Sauce',
        'Cocktail Sauce',
        'Hot Sauce',
        'Ketchup',
        'Mayonnaise',
        'Mustard',
        'Salsa',
        'Soy Sauce',
        'Steak Sauce',
        'Sweet and Sour Sauce',
        'Teriyaki Sauce'
    ]},

    {'Dairy': [
        'Almond Milk',
        'Butter',
        'Cheddar Cheese',
        'Cream',
        'Cream Cheese',
        'Half & Half',
        'Milk',
        'Mozzarella Cheese',
        'Provolone Cheese',
        'Pudding',
        'Skim Milk',
        'Soy Milk',
        'Swiss Cheese',
        'Whipped Cream',
        'Yogurt'
    ]},

    {'Meats': [
        'Beef Patty',
        'Bacon',
        'Bologna',
        'Chicken',
        'Fried Chicken',
        'Ham',
        'Pastrami',
        'Prosciutto',
        'Roast Beef',
        'Sausage',
        'Salami',                
        'Turkey'
    ]},

    {'Oils': [
        'Canola Oil',
        'Corn Oil',
        'Extra Virgin Olive Oil',
        'Olive Oil',
        'Peanut Oil',
        'Safflower Oil',
        'Soybean Oil',
        'Vegetable Oil'
    ]},

    {'Pasta': [
        'Angel Hair',
        'Ditalini',
        'Fettuccine',
        'Gemelli',
        'Linguine',
        'Mostaccioli',
        'Penne',
        'Rigatoni',
        'Rotini',
        'Shells',
        'Spaghetti',
        'Ziti'
    ]},

    {'Pasta Sauces': [
        'Alfredo Sauce',
        'Marinara Sauce',        
        'Tomato Sauce',
        'Vodka Sauce'
    ]},

    {'Pastry Mixes': [
        'Brownie Mix',
        'Cake Mix',
        'Cookie Mix',
        'Dessert Mix',
        'Pancake Mix'
    ]},

    {'Pickled Vegetables': [ 
        'Pickled Artichoke Hearts',
        'Pickled Blueberries',
        'Pickled Capers',
        'Pickled Cucumbers',
        'Pickled Eggplants',
        'Pickled Hot Peppers',
        'Pickled Mushrooms',
        'Pickled Olives',
        'Pickled Pepperoncini',
        'Pickled Raspberries',
        'Pickled Tomatoes',
        'Relish'
    ]},

    {'Salad Dressings': [
        'Balsamic Vinaigrette',
        'Blue Cheese Dressing',
        'Buffalo Ranch Dressing',
        'Creamy Caesar Dressing',
        'Creamy Italian Dressing',
        'Deluxe French Dressing',
        'Honey Mustard Dressing',
        'Italian Dressing',
        'Onion Dressing',
        'Ranch Dressing',
        'Raspberry Vinaigrette',
        'Russian Greek Vinaigrette',
        'Spicy Caesar Dressing',
        'Thousand Island Dressing'
    ]},

    {'Seafood': [
        'Anchovies',
        'Albacore Tuna',
        'Clams',
        'Herring',
        'Oysters',
        'Salmon',
        'Sardines',
        'Tuna',
        'White Albacore Tuna'
    ]},

    {'Soups': [
        'Beef Noodle Soup',
        'Beef with Rice Soup',
        'Cheddar Cheese Soup',
        'Chicken Noodle Soup',
        'Chicken Rice Soup',
        'Cream of Asparagus',
        'Creamy Chicken Noodle Soup',
        'Cream of Broccoli',
        'Cream of Mushroom Soup',
        'Golden Mushroom Soup',
        'Italian Style Wedding Soup',
        'Minestrone Soup',
        'New England Clam Chowder',
        'Spicy Vegetable Chili',
        'Tomato Soup',
        'Vegetable Soup'
    ]},

    {'Stocks': [
        'Beef Stock',
        'Chicken Stock',
        'Clam Stock',
        'Fish Stock',
        'Pork Stock',
        'Seafood Stock',
        'Veal Stock',
        'Vegetable Stock'
    ]},

    {'Vegetables': [
        'Beets',
        'Black Beans',
        'Black Eye Peas',
        'Broccoli',
        'Cannellini Beans',
        'Carrots',
        'Chick Peas',
        'Corn',
        'Fava Beans',
        'Green Beans',
        'Kidney Beans',
        'Lentils',
        'Lettuce',
        'Mixed Vegetables',
        'Peas',
        'Peas and Carrots',
        'Pinto Beans',
        'Potatoes',
        'Sauerkraut',
        'Spinach'
    ]},

    {'Vinegars': [
        'Apple Cider Vinegar',
        'Balsamic Vinegar',
        'Beer Vinegar',
        'Cane Vinegar',
        'Distilled White Vinegar',
        'Malt Vinegar',
        'Rice Vinegar',
        'Raisin Vinegar',
        'White Vinegar',
        'Wine Vinegar'
    ]}
]

known_nutrients = [
    ('Calories', True),
    ('Total Fat', True),
    ('Cholesterol', True),
    ('Sodium', True),
    ('Total Carbohydrate', True),
    ('Dietary Fiber', True),
    ('Sugars', True),
    ('Protein', True),
    ('Calories from Fat', False),
    ('Saturated Fat Calories', False),
    ('Saturated Fat', False),
    ('Monounsaturated Fat', False),
    ('Polyunsaturated Fat', False),
    ('Potassium', False),
    ('Soluble Fiber', False),
    ('Insoluble Fiber', False),
    ('Other Carbohydrate', False),
]

known_allergens = [
    ('Egg', True),
    ('Gluten', True),
    ('Lactose', True),
    ('Peanuts', True),
    ('Cereals', False),
    ('Coconut', False),
    ('Corn', False),
    ('Fish', False),
    ('Milk', False),
    ('Sesame Seeds', False),
    ('Shellfish', False),
    ('Soybean', False),
    ('Sulfites', False),
    ('Tree Nuts', False),
    ('Wheat', False),
]

known_additives = [
    ('Added Sugar', True),
    ('Artificial Color', True),
    ('Artificial Flavoring Agent', True),
    ('Emulsifiers', True),
    ('Flavor Enhancer', True),
    ('Preservatives', True),
    ('Sweeteners', True),
    ('Trans Fat', True),
    ('Acidity Regulator', False),
    ('Anti-Caking Agents', False),
    ('Anti-Foaming Agent', False),
    ('Antioxidants', False),
    ('Artificial Preservative', False),
    ('Bulking Agents', False),
    ('Colors', False),
    ('Enzyme', False),
    ('Firming Agent', False),
    ('Flour Treating Agent', False),
    ('Food Acids', False),
    ('Gelling Agents', False),
    ('Glazing Agent', False),
    ('Humectants', False),
    ('Leavening Agent', False),
    ('Mineral Salt', False),
    ('Natural Color', False),
    ('Natural Flavoring Agent', False),
    ('Natural Preservative', False),
    ('Propellant', False),
    ('Raising Agents', False),
    ('Saturated Fat', False),
    ('Sequestrant', False),
    ('Stabilizers', False),
    ('Thickeners', False),
    ('Unsaturated Fat', False),
    ('Vegetable Gum', False),
]

DAILY_VALUES = {
    # Name: (<string>, <in grams>)
    u'Total Fat': (u'65 g', 65.0),
    u'Saturated Fat': (u'20 g', 20.0),
    u'Cholesterol': (u'300 mg', 0.3),
    u'Sodium': (u'2,400 mg', 2.4),
    u'Potassium': (u'3,500 mg', 3.5),
    u'Total Carbohydrate': (u'300 g', 300.0),
    u'Dietary Fiber': (u'25 g', 25.0),
    u'Protein': (u'50 g', 50.0),
    u'Vitamin A': (u'5,000 IU', 0.0015),
    u'Vitamin C': (u'60 mg', 0.06),
    u'Calcium': (u'1,000 mg', 1.0),
    u'Iron': (u'18 mg', 0.018),
    u'Vitamin D': (u'400 IU', 0.00001),
    u'Vitamin E': (u'30 IU', 0.025),
    u'Vitamin K': (u'80 μg', 0.00008),
    u'Thiamin': (u'1.5 mg', 0.0015),
    u'Riboflavin': (u'1.7 mg', 0.0017),
    u'Niacin': (u'20 mg', 0.02),
    u'Vitamin B6': (u'2 mg', 0.002),
    u'Folate': (u'400 μg', 0.0004),
    u'Vitamin B12': (u'6 μg', 0.000006),
    u'Biotin': (u'300 μg', 0.0003),
    u'Pantothenic acid': (u'10 mg', 0.01),
    u'Phosphorus': (u'1,000 mg', 1.0),
    u'Iodine': (u'150 μg', 0.00015),
    u'Magnesium': (u'400 mg', 0.4),
    u'Zinc': (u'15 mg', 0.015),
    u'Selenium': (u'70 μg', 0.00007),
    u'Copper': (u'2 mg', 0.002),
    u'Manganese': (u'2 mg', 0.002),
    u'Chromium': (u'120 μg', 0.00012),
    u'Molybdenum': (u'75 μg', 0.000075),
    u'Chloride': (u'3,400 mg', 3.4),
}

UNIT_MULTIPLIER = {
    u'g': 1.0,
    u'mg': 0.001,
    u'μg': 0.000001,
}
